version: "3.9"

services:
  # text-review:
  #   container_name: 'text-review'
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   environment:
  #     TZ: Asia/Seoul
  #     PYTHONUNBUFFERED: 1      
  #   tty: true
  #   ipc: host
  #   stdin_open: true    
  #   restart: on-failure:3  
  #   volumes:
  #     - ./text-review/update_file:/text-review/update_file:rw      
  #   command: ["python3", "/text-review/main.py", "--date", $date]


  app:
    container_name: "markcloud-text-review-api"    
    build:
      context: ./
      dockerfile: Dockerfile
    image: "markcloud-text-review-api:1.0.0"
    env_file: .env
    volumes:
      - ./app:/app
    ports:
      - 8000:8080
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]


  nginx:
    container_name: "markcloud-text-review-web"
    build:
      context: ./webserver
      dockerfile: Dockerfile
    image: "markcloud-text-review-web:1.0.0"
    ports:
      - 7005:80
    volumes:
      - ./webserver/conf.d:/etc/nginx/conf.d


  # db:
  #   container_name: "markcloud-text-annotation-db"
  #   image: mongo:latest
  #   env_file: .env
  #   volumes:
  #     - ./data/db:/data/db
  #   ports:
  #     - 27017:27017